version: '3.3'
services:
  api:
    build: .
    ports: 
      - "${PORT}:${PORT}"
    depends_on: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '${MONGO_EXTERNAL_PORT}:${MONGO_PORT}'
    volumes:
      - ../mongo_data:/data/db